Repository pnp/PnP-Sites-Core, pull requests merged in 2018-12, with the labels that each got.

#1990 Feature - Enhanced UnifiedGroups provisioning
  Core/OfficeDevPnP.Core/Framework/Graph/UnifiedGroupsUtility.cs
Labels: To be processed

#1727 Add token parsing when provisioning search settings
  Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectSearchSettings.cs
Labels: To be processed

#1756 Feature - Ability to enable/disable comments, likes and view count on…
  Core/OfficeDevPnP.Core/Extensions/TenantExtensions.cs
Labels: To be processed

#1761 Fix issue #1656
  Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTermGroups.cs
Labels: waiting-for-clarification

#1857 Fix - Skip calling of Tenant and ALM handlers when not needed , null check in
  Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectApplicationLifecycleManagement.cs
  Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTenant.cs
Labels: Investigation needed
